
/***********************************************************************
MODULE:    Timers
VERSION:   1.00
CONTAINS:  Routines for controlling the timers on the Philips
           P89LPC922
COPYRIGHT: Embedded Systems Academy, Inc. - www.esacademy.com
LICENSE:   May be freely used in commercial and non-commercial code
           without royalties provided this copyright notice remains
           in this file and unaltered
WARNING:   IF THIS FILE IS REGENERATED BY CODE ARCHITECT ANY CHANGES
           MADE WILL BE LOST. WHERE POSSIBLE USE ONLY CODE ARCHITECT
           TO CHANGE THE CONTENTS OF THIS FILE
GENERATED: On "Nov 09 2007" at "18:15:33" by Code Architect 2.11
***********************************************************************/

#ifndef _TIMERSH_
    #define _TIMERSH_

    // ----------------------------
    // Seznam casovacu         
    // ----------------------------
    #define  TIMER_LED    timer[0]
    #define  TIMER_PIR    timer[1]
    // ----------------------------
    #define  TIMERS_COUNT       2


    /***********************************************************************
    DESC:    Initializes timers
             Timer 0 generates an interrupt every 10ms
             Timer 1 is not used
    RETURNS: Nothing
    CAUTION: If interrupts are being used then EA must be set to 1
             after calling this function
    ************************************************************************/
    extern void timers_init(void);

    extern int idata timer[TIMERS_COUNT];

#endif // _TIMERSH_


